version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - apt-get install -y git
  build:
    commands:
      - git clone https://github.com/edward-of-clt/codepipeline-test.git
